
######################## Introductory lines
# install the different packages that you will need
install.packages("rgdal")
install.packages("ape")
install.packages("vegan")
install.packages("SpatialTools")
install.packages("betapart")
install.packages("pvclust")
install.packages("caret")
install.packages("mapr")
install.packages("rgbif")
install.packages("dismo")
install.packages("mapplots")
install.packages("BiodiversityR")
install.packages("corrplot")
install.packages("MuMIn")
install.packages("car")
install.packages("pbkrtest")
install.packages("ggmap")
install.packages("gstat")
install.packages("tidyverse")


library("rgdal")
library("ape")
library("vegan")
library("SpatialTools")
library("betapart")
library("pvclust")
library("caret")
library("mapr")
library("rgbif")
library("dismo")
library("mapplots")
library("BiodiversityR")
library("car")
library("corrplot")
library("MuMIn")
library("pbkrtest")
library("ggmap")
library("gstat")
library("tidyverse")