
######################## Introductory lines
# install the different packages that you will need

install.packages("tidyverse")
install.packages("dplyr")
install.packages("tidyr")
install.packages("MuMIn")
install.packages("caret")
install.packages("corrplot")
install.packages("GGally")
install.packages("lme4")
install.packages("lmerTest")
install.packages("ggplot2")
install.packages("vegan")
install.packages("AER")
install.packages("MASS")
install.packages("car")
install.packages("modEvA")
install.packages("lmtest")
install.packages("statmod")

library(tidyverse)
library(dplyr)
library(tidyr)
library(MuMIn)
library(caret)
library(corrplot)
library(GGally)
library(lme4)
library(lmerTest)
library(ggplot2)
library(vegan)
library(AER)
library(MASS)
library(car)
library(modEvA)
library(lmtest)
library(statmod)

